.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Bdale Garbee <bdale@gag.com>
.\"
.TH TARCAT 1 
.SH NAME
tarcat \- concatenates the pieces of a GNU tar multi-volume archive
.SH SYNOPSIS
.B tarcat 
files ...
.SH DESCRIPTION
The 
.B tarcat 
command simply concatenates the files from a GNU tar multi-volume 
archive into a single tar archive.
.SH SEE ALSO
.BR tar (1).
.SH AUTHORS
The
.B tarcat 
script was written by 
Bruno Haible <bruno@clisp.org> and
Sergey Poznyakoff <gray@gnu.org.ua>.
.PP
This document was written by Bdale Garbee <bdale@gag.com> for Debian.

